# Site settings
title: Solace Samples OpenMAMA
summary: These tutorials get you up to speed sending and receiving messages with Solace technology.
baseurl: "/solace-samples-openmama" # the subpath of your site, e.g. /solace-samples-java
repository: https://github.com/SolaceSamples/solace-samples-openmama

# Also see _includes/intro.html to customize the description which gets included in index.html.

# Links
link-portal: http://dev.solace.com
link-tech: http://dev.solace.com/tech/
link-tech-vmr: http://dev.solace.com/tech/virtual-message-router/
link-community: http://dev.solace.com/community/
link-support: http://dev.solace.com/support/
link-downloads: http://dev.solace.com/downloads/
link-tech-openmama: http://dev.solace.com/tech/openmama/
links-solaceCloud-setup: http://cloud.solace.com/create-messaging-service/
docs-vmr-setup: http://docs.solace.com/Solace-VMR-Set-Up/Setting-Up-VMRs.htm
docs-solace-concepts: http://docs.solace.com/Features/Core-Concepts.htm
docs-openmama-concepts: http://docs.solace.com/Solace-OpenMama/Solace-OpenMAMA-Overview.htm
docs-openmama-bridges: http://docs.solace.com/Solace-OpenMama/Configuring-Solace-OpenMAMA-Bridges.htm
docs-sdkperf: http://docs.solace.com/SDKPerf/SDKPerf.htm

#----------------------------------------------------
# Generally don't modify items below this point
url: "solacesamples.github.io" # the base hostname & protocol for your site

# Google services
google_analytics: UA-3921398-7

# Build settings
markdown: kramdown

collections:
  tutorials:
    output: true
    permalink: /:path/
